### PR TITLE
Add ready EK plugins

### PR DESCRIPTION
**Pull request by tcrsavage**
All disabled by default while we do discovery

### CODE REVIEW

**Comment by owaincuvelier** [comment]
Has there been any talk about forking the external plugins? I think it'd be pretty cool to have a consistent HM brand.

**Comment by tcrsavage** [comment]
Yeah it's a likely scenario moving forward but we also want to avoid taking ownership of every feature of EK. Means a LOT of work.

**Comment by joehoyle** [comment]
@tcrsavage I think not for branding, but I do think we should fork these repos. As it stands right now, any 3rd party could remove / change the github repo and we'd be pulling in code (or not being able to pull in code) on deploy, and potentially break things. I'd say we should fork and use all github.com/humanmade repos/

**Comment by roborourke** [comment]
Fair point. Plus I'd like to make sure whatever we add has complete docblocks, at least down the line.

**Comment by tcrsavage** [comment]
Sounds good, will fork and update remotes

**Comment by tcrsavage** [comment]
Done

**Pull request merged**
