### PR TITLE
Add support for Redis as an object cache

### PR DESCRIPTION
**Pull request by nathanielks**
Includes `wp-redis` and `wp-redis-predis-client`.

### CODE REVIEW

**Comment by nathanielks** [comment]
@joehoyle `wp-redis-predis-client` is designed to work with composer, so I just realized that simply including it as a submodule won't work, it needs to have the composer deps installed as well. Curious your thoughts: should I include the plugin files in this repo and not as a submodule, or should I update the base repo with all the files and include it here as a submodule?

**Comment by nathanielks** [comment]
Other than that, I've got this working locally! woohoo!

**Comment by joehoyle** [comment]
Hmm good question. I'd probably not include it as a submodule, and commit the whole thing in that case :/

**Comment by nathanielks** [comment]
Of import is https://github.com/humanmade/hm-platform/pull/20/files#diff-d0bbf8b11aad6d313a864263bc2c4707. It unfortunately gets lost in the shuffle of all the files from `wp-redis-repdis-client`

**Comment by nathanielks** [comment]
(It's found at the very bottom of the diff)

**Comment by nathanielks** [comment]
@joehoyle I thought Batcache was working with this but it appears to not be. I _believe_ they built wp-redis to be compatible. Do we desire this?

**Comment by joehoyle** [comment]
Hmm Batcache doesn't have any reliance on memcached, so if it isn't working it would indicate a problem with Redis to me, as batcache only uses the normal WP Object Cache API

**Comment by nathanielks** [comment]
Yea, for some reason the html comment at the beginning of file isn't present with wp-redis at all. I'll dive deeper!


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.8.81&pv=7.0&source=email_footer_2] On Tue, Oct 24, 2017 at 12:21am, Joe Hoyle < notifications@github.com [notifications@github.com] > wrote:
Hmm Batcache doesn't have any reliance on memcached, so if it isn't working it would indicate a problem with Redis to me, as batcache only uses the normal WP Object Cache API

**Comment by nathanielks** [comment]
Ah, turns out I was being silly! I had `WP_CACHE` disabled while I was building out the redis integration and forgot to turn it back on. This is gtg @joehoyle!

**Comment by nathanielks** [comment]
Ready to merge, @joehoyle !

**Pull request merged**
