### PR TITLE
Merge beta branch

### PR DESCRIPTION
**Pull request by roborourke**
I've tagged this as v2.0.0 as it's a big change in the changelog, readme and the `package.json` file. Any other thoughts on that decision welcome.

This is backwards compatible with the `$hm_platform` global.

Visually speaking there should be no immediate changes when updating, the platform UI plugin is disabled by default via the plugin manifest.

### CODE REVIEW

**Comment by joehoyle** [comment]
@roborourke it seems like some of the deps here as switching to older versions. E.g. tachyon is switching to an earlier commit I think.

**Comment by roborourke** [comment]
Hmm, sorry must’ve not updated that. Was a bit of a complicated merge
regarding conflicts

**Comment by nathanielks** [comment]
@roborourke holler whenever this is ready for review!

**Comment by Japh** [comment]
I'm wondering if this is really a v2.0, or should actually be a separate repo in some way. Seems like there are quite a lot of very significant and probably breaking changes?

**Comment by rmccue** [comment]
I was chatting to @roborourke about this last week; I think we're in favour of splitting it given the evolution that has taken place here, provided we keep a mechanism to allow the UI to configure `hm-platform` components.

**Comment by roborourke** [comment]
The core part of it doesn't have any breaking changes, it's back compatible with `master`.

However a few things would need to happen to make the split, most notably around:

- which plugins are cloud & which are EK
- split the UI (make it pluggable) - do we also split the docs? Or make a way to tailor the docs site eg. no-ek, no-cloud
- duplicate the loading logic, it'd be nice to be able to use `hm.json` for both this repo and/or EK

**Comment by joemcgill** [comment]
@roborourke, @joehoyle, @rmccue. What's the status of this PR? Does this still reflect the direction things are going?

**Comment by rmccue** [comment]
@joemcgill Not really, we're moving towards a different approach, and this repo will likely become the Cloud module eventually. However, the beta branch is in use on some projects, so it's still maintained for that.

**Comment by joemcgill** [comment]
Thanks @rmccue, that's what I suspected. Hypothetically speaking, if a new project were using this branch, how would you suggest they take advantage of the new direction Platform is going without incurring undue technical debt. Should they switch back to the master branch for now, feel free to go ahead knowing that this is now a stale branch, or should they keep an eye out for new features coming into master over time?

**Comment by roborourke** [comment]
@joemcgill I guess switch to master for now. This was my concern with adopting the current EK on a project really, just the amount of churn there was. I can help with implementing some specific features in the meantime.

**Comment by roborourke** [comment]
Big RIP

**Pull request closed without merging**
