### PR TITLE
Fix Platform loading by using Plugin API functions.

### PR DESCRIPTION
**Pull request by fklein-lu**

### CODE REVIEW

**Comment by joehoyle** [comment]
Why is this going in to `beta`? is it a general fix, or is it needed specifically for the EK work?

**Comment by roborourke** [comment]
@joehoyle just fixes unit test runs, platform runs fine without it

**Comment by joehoyle** [comment]
I'm thinking it would make sense to not push too much to `beta` as it's going to get progressively more difficult to roll out `beta` the larger the release gets. Something like this I feel like might be a classic example of that - it has the potential to cause issues (say across WP versions) so if it's not tied to `beta` we should try push a smaller releases through the `master` channel.

**Comment by roborourke** [comment]
I guess ultimately the main change in a roll out of `beta` after this sprint would be adding a JSON config to the target repos we're updating.

I've been viewing this as a major version release so trying to build on it incrementally and merge things to master felt like it would slow us down given that there are some fundamental changes we're working on.

Also wanted to avoid disrupting usual maintenance and updates to the master branch while we work on it.

I can make a PR for the same change against `master` at any rate. What would your recommendation be going forward?

**Comment by joehoyle** [comment]
Ok - just to be clear, we need full backwards compatibility for merging `beta`, that means supporting the `global $hm_platform` config going forward, and not requiring an addition of a package.json, at least without a staged process (removing support for the current config object in the future).

In regards to general process, I mentioned `master` here, as it doesn't seem this patch has any reliance on the code in `beta`, therefor I think it's better to have a "continues deployment" stance by default. EK I'm presuming needs a bit release, but we should still aim to be as incremental wherever we can.

**Pull request merged**
