### PR TITLE
Add Healthcheck endpoint.

### PR DESCRIPTION
**Pull request by joehoyle**
A `/healthcheck/` endpoint should always be available now.

### CODE REVIEW

**Comment by nathanielks** [comment]
@joehoyle is this ready for review?

**Comment by joehoyle** [comment]
@nathanielks yup!

**Comment by joehoyle** [comment]
I took another stab at this after thinking about some of the issues in https://github.com/humanmade/hosting-support/issues/205. This pulls things out a bit better:

- Checks are passed through a filter so 3rd parties / plugins etc could add their own checks
- Check for object-cache in sync for alloptions
- WP CLI command for running checks
- Checks for cron array
- Support for getting the checks as JSON with the `Accept: application/json` header.

**Comment by joehoyle** [comment]
@nathanielks for another review if you don't mind.

**Comment by joehoyle** [comment]
```bash
# wp --allow-root  healthcheck run
+---------------+------------------------------------------+
| check         | status                                   |
+---------------+------------------------------------------+
| mysql         | Passed                        |
| object-cache  | Passed                        |
| cron          | 8 jobs passed their run date. |
| elasticsearch | Passed                        |
+---------------+------------------------------------------+
```

**Comment by owaincuvelier** [comment]
Love this!

**Comment by nathanielks** [comment]
One side effect I just realized is the cron healthcheck is SC is going to be affected by this. We'll be using this for our EC2 instances, yeah? Does their constant failed jobs mean we'll be churning instances?

**Comment by joehoyle** [comment]
@nathanielks the idea is never to shut down an instance based off these checks, they are more for the whole application health, so we'd show alerts for them, but they'd typically just mean we needed to manually look into what the problem was.

**Comment by nathanielks** [comment]
cool cool cool 👍

**Pull request merged**
