### PR TITLE
Send PHP Logs to CloudWatch

### PR DESCRIPTION
**Pull request by joehoyle**
Application layer PHP error handler to send structured errors with XRay (part of the XRay plugin) integration.

I think we might only want to activate on ECS, because (though not in this PR) this uses a Log Group that doesn't exist elsewhere.

### CODE REVIEW

**Comment by nathanielks** [comment]
@joehoyle will this report errors both to a general, catch-all stream as well as a error-level specific stream? I see value in being able to see all warnings/errors in chronological order, as you can see what leads up to a fatal, or other warnings surrounding a fatal. Or maybe we can combine the error-specific streams into one elsehwhere for the same effect 🤔

**Comment by joehoyle** [comment]
@nathanielks CloudWatch does support pulling from multiple steams with interweaved=1, granted that's not _perfect_ which might be what you are getting at?

**Comment by nathanielks** [comment]
@joehoyle 	yup, that's exactly it 👍  We can always ensure sorting when displaying that info!

**Comment by joehoyle** [comment]
@nathanielks sorry I'm not super clear on what you are saying above: do you think we should also push to an ALL stream, or that doing interweaved is ok?

**Comment by joehoyle** [comment]
@nathanielks Ok this is ready for review, I've enabled it only on ECS, as that's the only place we have the log group atm.

**Pull request merged**
