### PR TITLE
Add final database query to X-Ray

### PR DESCRIPTION
**Pull request by Nikschavan**
See #183

### CODE REVIEW

**Comment by joehoyle** [comment]
Hmm I'm not sure if this is the right approach. Is the filter naturally called higher up in the call stack that `wpdb::query`? Wondering if we can capture the query at a different point. As it is, something that might hook`query` would erroneously see queries that are not _actually_ sent to mysql for querying.

**Comment by Nikschavan** [comment]
> Is the filter naturally called higher up in the call stack that wpdb::query

I would say the filter is run just before the query is executed, Also AFAIK this is the last filter available before the query is executed.

So I am thinking any other queries will not get added to this filter which is not supposed to be executed?

https://github.com/WordPress/WordPress/blob/32edd58e4c8e42b68813e3b92886aaa3e50cc1a9/wp-includes/wp-db.php#L1888-L1912

Another solution to removing the placeholders would be to pass the query from [`remove_placeholder_escape()`](https://github.com/WordPress/WordPress/blob/32edd58e4c8e42b68813e3b92886aaa3e50cc1a9/wp-includes/wp-db.php#L2134-L2136)

But that will miss if any query is being modified using this `query` filter.

Let me know what you think would be the right approach.

**Comment by joehoyle** [comment]
It looks like we could instead replace `_do_query()` in this subclass, as that gets passed the query after placeholders etc have been replaced. I think that would be a better approach.

**Comment by Nikschavan** [comment]
Right, that will work. 

Also looking more into this, Looks like in the current `query()` method, instead of the variable `$query` we can use [`$this->last_query`](https://github.com/WordPress/WordPress/blob/32edd58e4c8e42b68813e3b92886aaa3e50cc1a9/wp-includes/wp-db.php#L1909-L1910) which is already filtered and will have the final version of the query being executed.

**Comment by Nikschavan** [comment]
@joehoyle Let me know if you think using `$this->last_query` would be good and I will update the PR accordingly.

**Comment by joehoyle** [comment]
@Nikschavan I'm suggesting we change our overriden mathed to `_do_query` rather than overwriting a new one. I think `$this->last_query` is less guerenteed, as it might be possible for that value to be something other than the query passed to `query()` (e.g. future changed, or `select found rows()` etc.

**Comment by Nikschavan** [comment]
@joehoyle I have changed the PR, Instead of overriding `query()` now I am overriding `_do_query()` as it seems `query()` was being overridden only for sending the segment to X-Ray.

**Comment by joehoyle** [comment]
I think we should also port this to https://github.com/humanmade/altis-cloud/blob/master/inc/class-db.php

**Pull request merged**
